
// Objective-C API for talking to the following Go packages
//
//	twitter-stream-aggregator-2/twitter
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Twitter_FRAMEWORK_H__
#define __Twitter_FRAMEWORK_H__

#include "Twitter.objc.h"
#include "Universe.objc.h"

#endif
